[project]
name = "peerreview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "holdrain47", email = "holdrain47@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
peerreview = "peerreview:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
